# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: bean
networks:
- id: 42161
  start_block: 0
  contracts:
  - name: Bean
    address:
    - 0xBEA0005B8599265D41256905A9B3073D397812E4
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: EIP712DomainChanged()
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
rollback_on_reorg: false
